PACKAGE_NAME="ipu6-drivers"
PACKAGE_VERSION="#MODULE_VERSION#"
BUILD_EXCLUSIVE_KERNEL="^(5\.(1[05])\.|6\.[1568]\.|6\.(1[12])\.)"

#Extract kernel version substring that is used to identify source directory for kernel modules
# i.e 4.4.0-116-generic ==>  4.4.0
SELECTED_KERNEL=$(echo $kernelver | cut -d- -f1 | sed -r 's/(.*?)\..*/\1.0/g')
SELECTED_KERNEL_PATCH=$(echo $kernelver | cut -d- -f2)

MAKE="if [ -f $kernel_source_dir/tools/bpf/resolve_btfids/resolve_btfids ] && [ -f /sys/kernel/btf/vmlinux ]; then ln -s /sys/kernel/btf/vmlinux $kernel_source_dir/vmlinux; fi ;make V=1 KERNELRELEASE=$kernelver KERNEL_SRC=$kernel_source_dir"
CLEAN="if [ -f $kernel_source_dir/vmlinux ]; then rm $kernel_source_dir/vmlinux; fi ; make V=1 KERNELRELEASE=$kernelver KERNEL_SRC=$kernel_source_dir clean"
AUTOINSTALL="yes"
BUILD_EXCLUSIVE_CONFIG="CONFIG_VIDEO_V4L2_I2C"

version_lt() {
  IFS='.' read -r i j k <<< "$1"
  IFS='.' read -r a b c <<< "$2"
  i=${i:-0}
  j=${j:-0}
  k=${k:-0}
  a=${a:-0}
  b=${b:-0}
  c=${c:-0}
  if [ "$i" -lt "$a" ]; then
    return 0
  elif [ "$i" -eq "$a" ]; then
    if [ "$j" -lt "$b" ]; then
      return 0
    elif [ "$j" -eq "$b" ]; then
      if [ "$k" -lt "$c" ]; then
        return 0
      fi
    fi
  fi
  return 1
}

KERNEL_VERSION=$(echo ${kernelver} | sed 's/[^0-9.]*\([0-9.]*\).*/\1/')
KV_IPU6_ISYS_UPSTREAM=6.14.0

#Patches for Kernel 6.1
PATCH[0]="0001-videodev2-camera-formats-6.1.patch"
PATCH_MATCH[0]="^(6\.[1568]\.|6\.(1[12])\.)"

PATCH[1]="0001-v6.10-IPU6-headers-used-by-PSYS.patch"
PATCH_MATCH[1]="^(6\.(1[12])\.)"

i=0

BUILT_MODULE_NAME[$i]="ar0234"
BUILT_MODULE_LOCATION[$i]="drivers/media/i2c"
DEST_MODULE_LOCATION[$i]="/updates"
STRIP[$i]=no

BUILT_MODULE_NAME[$((++i))]="lt6911uxc"
BUILT_MODULE_LOCATION[$i]="drivers/media/i2c"
DEST_MODULE_LOCATION[$i]="/updates"
STRIP[$i]=no

BUILT_MODULE_NAME[$((++i))]="imx390"
BUILT_MODULE_LOCATION[$i]="drivers/media/i2c"
DEST_MODULE_LOCATION[$i]="/kernel/drivers/media/i2c"
STRIP[$i]=no

BUILT_MODULE_NAME[$((++i))]="intel-ipu6-psys"
BUILT_MODULE_LOCATION[$i]="drivers/media/pci/intel/ipu6/psys"
DEST_MODULE_LOCATION[$i]="/updates"
STRIP[$i]=no

BUILT_MODULE_NAME[$((++i))]="ipu6-acpi"
BUILT_MODULE_LOCATION[$i]="drivers/media/platform/intel"
DEST_MODULE_LOCATION[$i]="/updates"
STRIP[$i]=no

BUILT_MODULE_NAME[$((++i))]="ipu6-acpi-pdata"
BUILT_MODULE_LOCATION[$i]="drivers/media/platform/intel"
DEST_MODULE_LOCATION[$i]="/updates"
STRIP[$i]=no

BUILT_MODULE_NAME[$((++i))]="ipu6-acpi-common"
BUILT_MODULE_LOCATION[$i]="drivers/media/platform/intel"
DEST_MODULE_LOCATION[$i]="/updates"
STRIP[$i]=no

BUILT_MODULE_NAME[$((++i))]="d4xx-max9295"
BUILT_MODULE_LOCATION[$i]="drivers/media/i2c"
DEST_MODULE_LOCATION[$i]="/updates"
STRIP[$i]=no

BUILT_MODULE_NAME[$((++i))]="d4xx-max9296"
BUILT_MODULE_LOCATION[$i]="drivers/media/i2c"
DEST_MODULE_LOCATION[$i]="/updates"
STRIP[$i]=no

BUILT_MODULE_NAME[$((++i))]="d4xx"
BUILT_MODULE_LOCATION[$i]="drivers/media/i2c"
DEST_MODULE_LOCATION[$i]="/updates"
STRIP[$i]=no

#if version_lt ${KERNEL_VERSION} ${KV_IPU6_ISYS_UPSTREAM}; then
    BUILT_MODULE_NAME[$((++i))]="intel-ipu6"
    BUILT_MODULE_LOCATION[$i]="drivers/media/pci/intel/ipu6"
    DEST_MODULE_LOCATION[$i]="/updates"
    STRIP[$i]=no

    BUILT_MODULE_NAME[$((++i))]="intel-ipu6-isys"
    BUILT_MODULE_LOCATION[$i]="drivers/media/pci/intel/ipu6"
    DEST_MODULE_LOCATION[$i]="/updates"
    STRIP[$i]=no
#fi
