#!/bin/bash
# file: rs_ipu6_d457_bind.sh
# This script used for binding media links of v4l2 subdevice entities
# The configuration we had is DS5 mux and IPU6 entities.
# _______  _______  _______  _______  _________
# |depth|->| mux |->|CSI-2|->|BESOC|->|capture|
# |_____|  |_____|  |_____|  |_____|  |_______|
#
# Full graph can be viewed on http://magjac.com/graphviz-visual-editor/
# media graph links can be generated by running 'media-ctl --print-dot'
#
# Dependency: v4l-utils
v4l2_util=$(which v4l2-ctl)
media_util=$(which media-ctl)
if [ -z ${v4l2_util} ]; then
  echo "v4l2-ctl not found, install with: sudo apt install v4l-utils"
  exit 1
fi
# enable metadata capture nodes for default
metadata_enabled=1
while [[ $# -gt 0 ]]; do
  case $1 in
    -q|--quiet)
      quiet=1
      shift
    ;;
    -m|--mux)
      shift
      mux_param=$1
      shift
    ;;
    -n|--no-metadata)
      metadata_enabled=0
      shift
    ;;
    -h|--help)
      echo "-q -m -n -h"
    ;;
    *)
      quiet=0
      shift
    ;;
    esac
done

# mapping for DS5 mux entity to IPU6 BE SOC entity matching.
declare -A media_mux_capture_link=( [a]='' [b]='1 ' [c]='2 ' [d]='3 ' [e]='4 ' [f]='5 ' [g]='' [h]='1 ' [i]='2 ' [j]='3 ' [k]='4 ' [l]='5 ' [A]='' [E]='4 ' [G]='' [H]='' [I]='' [J]='' [K]='4 ' [L]='4 ' [M]='4 ')
# mapping for DS5 mux entity to IPU6 CSI-2 entity matching.
declare -A media_mux_csi2_link=( [a]=0 [b]=1 [c]=2 [d]=3 [e]=4 [f]=5 [g]=0 [h]=1 [i]=2 [j]=3 [k]=4 [l]=5 [A]=0 [E]=4 [G]=0 [H]=0 [I]=0 [J]=0 [K]=4 [L]=4 [M]=4 )

# all available DS5 muxes, each one represent physically connected camera.
# muxes a, b, c, d, e, f  usually single link cameras
# muxes g, h, i, i, k, l is aggregated link cameras, 'a' coupled to 'g'

mux_list=${mux_param:-'a b c d e f g h i j k l A E G H I J K L M'}
# Find media device.
# For case with usb camera plugged in during the boot,
# usb media controller will occupy index 0
mdev=$(${v4l2_util} --list-devices | grep -A1 ipu6 | grep media)
[[ -z "${mdev}" ]] && exit 0

media_ctl_cmd="${media_util} -d ${mdev}"
#media-ctl -r # <- this can be used to clean-up all bindings from media controller
# cache media-ctl output
dot=$($media_ctl_cmd --print-dot)

fmt_depth="${fmt:-[fmt:UYVY8_1X16/640x480@1/30 field:none]}"
fmt_rgb="${fmt:-[fmt:VYUY8_1X16/640x480@1/30 field:none]}"
fmt_ir="${fmt:-[fmt:VYUY8_1X16/640x480@1/30 field:none]}"
# For fimware version starting from: 5.16,
# IMU will have 32bit axis values.
# 5.16.x.y = firmware version: 0x0510
# state->fw_version < 0x510
#fmt_imu="${fmt:-[fmt:Y8_1X8/32x1 field:none]}"
# state->fw_version >= 0x510
fmt_imu="${fmt:-[fmt:Y8_1X8/38x1@1/50 field:none]}"
out() {
  [[ $quiet -eq 0 ]] && echo -n "${@}    " >&2
  "${@}"
  [[ $quiet -eq 0 ]] && echo "        RET=$?" >&2
}


# DS5 MUX. Can be {a, b, c, d, e ,f } + Aggregated {g, h, i, j, k, l}.
for mux in $mux_list; do
  is_mux=$(echo "${dot}" | grep "DS5 mux ${mux}")
  # skip for non-existing muxes
  [[ -z $is_mux ]] && continue;

  [[ $quiet -eq 0 ]] && echo -n "Bind DS5 mux ${mux} .. "

  csi2_be_soc="CSI2 BE SOC ${media_mux_csi2_link[${mux}]}"

  csi2="CSI-2 ${media_mux_csi2_link[${mux}]}"
  # capture pad
  be_soc_cap="BE SOC ${media_mux_capture_link[${mux}]}capture"

  cap_pad=0
  # bind (enable) link CSI-2 pad 1 to BE-SOC pad 0
  $media_ctl_cmd -v -l "\"Intel IPU6 ${csi2}\":1 -> \"Intel IPU6 ${csi2_be_soc}\":0[1]" 1>/dev/null
  # bind (enable) link DS5 mux pad 0 to CSI-2 pad 0
  $media_ctl_cmd -v -l "\"DS5 mux ${mux}\":0 -> \"Intel IPU6 ${csi2}\":0[1]" 1>/dev/null

  # for DS5 aggregated mux (above d) - use BE-SOC capture pads with offset 6
  # this offset used as capture sensor set - dept+md,rgb+md,ir,imu = 6
  cap_pad=0
  if  [ "${mux}" \= "L" ] || [ "${mux}" \= "H" ]; then
	metadata_enabled=0
	cap_pad=1
  else
	if  [ "${mux}" \= "M" ] || [ "${mux}" \= "I" ]; then
		metadata_enabled=0
		cap_pad=7
	else
		if [ "${mux}" \> "f" ] || [ "${mux}" \> "E" ]; then
			cap_pad=6
		fi
	fi
  fi

  # DEPTH video streaming node
  $media_ctl_cmd -v -l "\"Intel IPU6 ${csi2_be_soc}\":$((${cap_pad}+1)) -> \"Intel IPU6 ${be_soc_cap} $((${cap_pad}+0))\":0[5]" 1>/dev/null
  # DEPTH metadata node
  if [[ $metadata_enabled -eq 1 ]]; then
    $media_ctl_cmd -v -l "\"Intel IPU6 ${csi2_be_soc}\":$((${cap_pad}+2)) -> \"Intel IPU6 ${be_soc_cap} $((${cap_pad}+1))\":0[5]" 1>/dev/null
  fi

  # RGB link video streaming node
  $media_ctl_cmd -v -l "\"Intel IPU6 ${csi2_be_soc}\":$((${cap_pad}+3)) -> \"Intel IPU6 ${be_soc_cap} $((${cap_pad}+2))\":0[5]" 1>/dev/null
  # RGB metadata node
  if [[ $metadata_enabled -eq 1 ]]; then
    $media_ctl_cmd -v -l "\"Intel IPU6 ${csi2_be_soc}\":$((${cap_pad}+4)) -> \"Intel IPU6 ${be_soc_cap} $((${cap_pad}+3))\":0[5]" 1>/dev/null
  fi

  if [ "${mux}" \= "L" ] || [ "${mux}" \= "H" ]; then
      # remap IR amd IMU suffix c to CSI2 input 13 and 14
      cap_pad=$((${cap_pad}+7))
  else
      if  [ "${mux}" \= "M" ] || [ "${mux}" \= "I" ]; then
	  # remap IR amd IMU suffix d to CSI2 input 15 and 16
	  cap_pad=$((${cap_pad}+3))
      fi
  fi

  # IR link video streaming node
  $media_ctl_cmd -v -l "\"Intel IPU6 ${csi2_be_soc}\":$((${cap_pad}+5)) -> \"Intel IPU6 ${be_soc_cap} $((${cap_pad}+4))\":0[5]" 1>/dev/null

  # IMU link streaming node
  $media_ctl_cmd -v -l "\"Intel IPU6 ${csi2_be_soc}\":$((${cap_pad}+6)) -> \"Intel IPU6 ${be_soc_cap} $((${cap_pad}+5))\":0[5]" 1>/dev/null

  # DEPTH default media bus format
  out $media_ctl_cmd -V "\"D4XX depth ${mux}\":0 ${fmt_depth}"
  out $media_ctl_cmd -V "\"DS5 mux ${mux}\":1 ${fmt_depth}"
  # RGB default media bus format
  out $media_ctl_cmd -V "\"D4XX rgb ${mux}\":0 ${fmt_rgb}"
  out $media_ctl_cmd -V "\"DS5 mux ${mux}\":2 ${fmt_rgb}"
  # IR default media bus format
  out $media_ctl_cmd -V "\"D4XX ir ${mux}\":0 ${fmt_ir}"
  out $media_ctl_cmd -V "\"DS5 mux ${mux}\":3 ${fmt_ir}"
  # IMU default media bus format
  out $media_ctl_cmd -V "\"D4XX imu ${mux}\":0 ${fmt_imu}"
  out $media_ctl_cmd -V "\"DS5 mux ${mux}\":4 ${fmt_imu}"

done
